"""empty message

Revision ID: 599f406a87ee
Revises: 
Create Date: 2024-02-21 16:06:44.982725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '599f406a87ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_code', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('verification_code')

    # ### end Alembic commands ###
