"""empty message

Revision ID: 67be5a030ec8
Revises: 599f406a87ee
Create Date: 2024-02-21 16:07:10.545108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67be5a030ec8'
down_revision = '599f406a87ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_token', sa.String(), nullable=True))
        batch_op.drop_column('verification_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_code', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('verification_token')

    # ### end Alembic commands ###
