"""empty message

Revision ID: c2fcc8f2fd51
Revises: bd53f9165236
Create Date: 2024-01-31 16:20:15.371735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2fcc8f2fd51'
down_revision = 'bd53f9165236'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed', sa.Boolean(), nullable=True))
        batch_op.drop_column('email_confirmed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_confirmed', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('confirmed')

    # ### end Alembic commands ###
